### ISSUE TITLE
Not compatible with package flutter_stripe: 

### ISSUE THREAD

**Issue by arslanriaz038** [pusher/pusher-channels-flutter#45]
When I Use FlutterFragmentActivity in MainActivity for Stripe Implementation in  Android side Pushser Crashes:

W/System.err(30237): SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
W/System.err(30237): SLF4J: Defaulting to no-operation (NOP) logger implementation
W/System.err(30237): SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
E/AndroidRuntime(30237): FATAL EXCEPTION: pusher-java-client eventQueue
E/AndroidRuntime(30237): Process: com.pass.more.plants, PID: 30237
E/AndroidRuntime(30237): java.lang.NullPointerException
E/AndroidRuntime(30237): 	at com.pusher.channels_flutter.PusherChannelsFlutterPlugin.callback(PusherChannelsFlutterPlugin.kt:90)
E/AndroidRuntime(30237): 	at com.pusher.channels_flutter.PusherChannelsFlutterPlugin.onConnectionStateChange(PusherChannelsFlutterPlugin.kt:209)
E/AndroidRuntime(30237): 	at com.pusher.client.connection.websocket.WebSocketConnection$4.run(WebSocketConnection.java:166)
E/AndroidRuntime(30237): 	at com.pusher.client.util.Factory$1.run(Factory.java:119)
E/AndroidRuntime(30237): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(30237): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(30237): 	at java.lang.Thread.run(Thread.java:920)
I/Process (30237): Sending signal. PID: 30237 SIG: 9
Lost connection to device.

**Comment by proggen-com** [comment]
Could you please check if this similar issue may resolve your problem? 
https://github.com/jdeferred/jdeferred/issues/124

**Comment by SlickSlime** [comment]
@proggen-com Updating `build.gradle` using [this](https://github.com/jdeferred/jdeferred/issues/124#issuecomment-338133380) comment helps in removing the `slf4j` error.
```
W/System.err(30237): SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
W/System.err(30237): SLF4J: Defaulting to no-operation (NOP) logger implementation
W/System.err(30237): SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

But the `NullPointerException` still persists with the following error log:
```
E/AndroidRuntime(30237): FATAL EXCEPTION: pusher-java-client eventQueue
E/AndroidRuntime(30237): Process: com.pass.more.plants, PID: 30237
E/AndroidRuntime(30237): java.lang.NullPointerException
E/AndroidRuntime(30237): at com.pusher.channels_flutter.PusherChannelsFlutterPlugin.callback(PusherChannelsFlutterPlugin.kt:90)
E/AndroidRuntime(30237): at com.pusher.channels_flutter.PusherChannelsFlutterPlugin.onConnectionStateChange(PusherChannelsFlutterPlugin.kt:209)
E/AndroidRuntime(30237): at com.pusher.client.connection.websocket.WebSocketConnection$4.run(WebSocketConnection.java:166)
E/AndroidRuntime(30237): at com.pusher.client.util.Factory$1.run(Factory.java:119)
E/AndroidRuntime(30237): at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(30237): at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(30237): at java.lang.Thread.run(Thread.java:920)
I/Process (30237): Sending signal. PID: 30237 SIG: 9
Lost connection to device.
```

**Comment by SlickSlime** [comment]
Created a temporary fix by replacing `FlutterActivity` with `FlutterFragmentActivity` in `PusherChannelsFlutterPlugin.kt` file.

Here is the commit in the forked repo: https://github.com/SlickSlime/pusher-channels-flutter/commit/c36fd352957dbedd02dcffe69a71f846c47f3322

I hope someone can help create a fix so that the `pusher_channels_flutter` plugin would work with `FlutterActivity` and `FlutterFragmentActivity`.

**Comment by proggen-com** [comment]
Hi SlickSlime, could you explain why that fixes the issue? FlutterFragmentActivity seems deprecated? Cheers.

**Comment by SlickSlime** [comment]
@proggen-com `flutter_stripe` requires us to extend our `MainActivity.kt` with `FlutterFragmentActivity` instead of `FlutterActivity` ([link](https://pub.dev/packages/flutter_stripe#requirements)). But the `PusherChannelsFlutterPlugin.kt` class is trying to look for `FlutterActivity`. So I just replaced all instances of `FlutterActivity` with `FlutterFragmentActivity` in `PusherChannelsFlutterPlugin.kt` too.

**Comment by arslanriaz038** [comment]
@SlickSlime Thanks I hope its gonna work out..

**Comment by benjamin-tang-pusher** [comment]
I will close this issue as you were able to find a workaround. FlutterFragmentActivity is deprecated so I don't think the Pusher flutter library is necessarily wrong.

**Comment by ilml1** [comment]
> I will close this issue as you were able to find a workaround. FlutterFragmentActivity is deprecated so I don't think the Pusher flutter library is necessarily wrong.

This is also an issue when working with local_auth, official plugin from flutter. FlutterFragmentActivity is needed for this plugin and doesnt appear as deprecated when I go to official docs from flutter.
https://api.flutter.dev/javadoc/io/flutter/embedding/android/FlutterFragmentActivity.html
You might've been checking the old one that was being imported from io.flutter.app, instead of the new one that is replacing the old FlutterFragmentActivity.
